.TH "alarm" 1 "2015-09-10" "GNU Command"


.SH NAME

.P
\fBalarm\fR alarm \- a program to notify when a user
 specified time has been reached.

.SH SYNOPSIS

.P
Cooking timer mode:

.P
\fBalarm\fR mm

.P
\fBalarm\fR mm:ss | mm: | :ss

.P
\fBalarm\fR hh:mm:[ss]

.P
Alarm clock mode:

.P
\fBalarm\fR \-a hh:mm:[ss] AM|PM (case insensitive)

.SH DESCRIPTION

.P
\fBalarm\fR notifies the user when the input time is reached.
By default the input time is added to the start time, in other words
cooking timer mode, but optionally an actual clock  time may be input,
ie alarm clock mode.

.SH OPTIONS

.TP
 \fB\-h\fR
print help information and exit.

.TP
 \fB\-a\fR
Interprets the input time as clock time, not an increment
from program start.
You should use the hh:mm:ss or hh:mm: time specifiers when using
this option.

.SH NOTES

.P
Times may be specified in 24 hour or AMPM format, case insensitive. If
PM is input then 12 hours will be added to the hours field if it's less
than  12 but not otherwise. The only range check is that no number
may be  negative. No other range check will be done. Consequently a 90
second interval may be input as :90 or 1:30.
In alarm mode the time specified will be the next occurrence of  that
time so if you input 6:00 at 9 am then the alarm will be scheduled for
6 am tomorrow. The actual alarm notification is done by running a movie
player to display a short musical clip. Such clip together with the
player is named in the file: \fI.config/alarm/alarm.txt.\fR
On first run that file will be installed but you will need to edit
this file to name your media player and the file to be played.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man alarm.t2t
